'use strict';
const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {setGlobalOptions}=require('firebase-functions/v2');
const admin=require('firebase-admin');
const crypto=require('crypto');
admin.initializeApp();
const db=admin.firestore();
const REGION='europe-west1';
const APP_ID='iis-levi-electoral-v3';
setGlobalOptions({region:REGION,maxInstances:20});
const STAFF_ROLES=new Set(['COMMISSIONE','DIRIGENTE','VICEPRESIDE','DSGA','SEGRETERIA']);
const SESSION_MS=15*60*1000;
const norm=v=>String(v??'').trim().toUpperCase();
const suffix=y=>{const s=String(y||'').trim();if(!/^20\d{2}\/20\d{2}$/.test(s))throw new HttpsError('invalid-argument','Anno scolastico non valido.');return s.replace('/','_')};
const root=()=>db.collection('artifacts').doc(APP_ID).collection('public').doc('data');
const col=(n,y)=>root().collection(`${n}_${suffix(y)}`);
const globalConfig=()=>root().collection('config').doc('settings_v3');
const yearlyConfig=y=>root().collection('config').doc(`yearly_settings_${suffix(y)}`);
const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const randomId=(bytes=32)=>crypto.randomBytes(bytes).toString('base64url');
function requireAuth(req,roles=[]){if(!req.auth)throw new HttpsError('unauthenticated','Autenticazione richiesta.');const r=norm(req.auth.token.role);if(roles.length&&!roles.includes(r))throw new HttpsError('permission-denied','Ruolo non autorizzato.');return{uid:req.auth.uid,role:r,scopeClass:norm(req.auth.token.scopeClass||'TUTTE'),name:String(req.auth.token.name||'')}}
async function cfg(year){const s=await yearlyConfig(year).get();if(!s.exists)throw new HttpsError('failed-precondition','Configurazione annuale non disponibile.');return s.data()||{}}
function parseIT(d,t){if(!/^\d{2}\/\d{2}\/\d{4}$/.test(d||'')||!/^\d{2}:\d{2}$/.test(t||''))return null;const[dd,mm,yy]=d.split('/').map(Number),[hh,mi]=t.split(':').map(Number);return new Date(Date.UTC(yy,mm-1,dd,hh-1,mi,0))}
async function phase(year){const c=await cfg(year),cal=c.calendario||{},now=Date.now(),start=parseIT(cal.votingStartDate,cal.votingStartTime),end=parseIT(cal.votingEndDate,cal.votingEndTime),rel=parseIT(cal.resultsReleaseDate,cal.resultsReleaseTime);if(start&&now<start.getTime())return{phase:'BEFORE',config:c};if(end&&now>end.getTime())return{phase:rel&&now>=rel.getTime()&&c.commissionFinalized===true?'RELEASED':'CLOSED',config:c};return{phase:'OPEN',config:c}}
async function audit(actor,action,meta={}){const safe={};for(const[k,v]of Object.entries(meta)){if(!/token|vote|ballot|session|prefer|candidate|lista/i.test(k))safe[k]=v}await root().collection('audit_admin').add({action,role:actor.role,uidHash:hash(actor.uid).slice(0,24),at:admin.firestore.FieldValue.serverTimestamp(),meta:safe})}
function verifyPwd(pw,data){if(!data.passwordHash||!data.passwordSalt)return false;try{return crypto.timingSafeEqual(Buffer.from(data.passwordHash,'hex'),crypto.scryptSync(pw,data.passwordSalt,64))}catch{return false}}
async function findStaff(username,year,role){const snap=await col('gestione_accessi',year).where('username','==',String(username||'').trim().toLowerCase()).where('role','==',role).limit(1).get();if(snap.empty)return null;const d=snap.docs[0];return{id:d.id,...d.data()}}
function tokenClaims(profile){return{role:norm(profile.role),scopeClass:norm(profile.scopeClass||'TUTTE'),name:String(profile.name||'')}}
async function staffCustomToken(profile){return admin.auth().createCustomToken(`staff_${profile.id}`,tokenClaims(profile))}
function activeFor(c,type){return type==='STUDENTE'?['istituto','consulta','classeStudente']:type==='GENITORE'?['consiglio','classeGenitore']:['consiglio']}
function flags(d){return{voted_consiglio:!!d.voted_consiglio,voted_istituto:!!d.voted_istituto,voted_consulta:!!d.voted_consulta,voted_classe_studente:!!d.voted_classe_studente,voted_classe_genitore:!!d.voted_classe_genitore}}
function storedBallot(v,kind,tokenData){const o={};if(kind==='consiglio'||kind==='istituto'||kind==='consulta'){o.lista=String(v.lista||'').trim();const ps=[v.p1,v.p2].map(x=>norm(x)).filter(Boolean);if(ps.length)o.preferenze=ps}else if(kind==='classeStudente'||kind==='classeGenitore'){o.isBianca=!!v.isBianca;if(!o.isBianca){o.candidate1=norm(v.candidate1);if(v.candidate2)o.candidate2=norm(v.candidate2)}o.classe=norm(tokenData.classe)}o.tipo=norm(tokenData.tipo);return o}
function ballotMeta(kind){return{consiglio:['voti_consiglio','voted_consiglio'],istituto:['voti_istituto','voted_istituto'],consulta:['voti_consulta','voted_consulta'],classeStudente:['voti_classe_studenti','voted_classe_studente'],classeGenitore:['voti_classe_genitori','voted_classe_genitore']}[kind]}
function validateBallot(kind,v,c,td){const m=ballotMeta(kind);if(!m)throw new HttpsError('invalid-argument','Scheda non prevista.');const type=norm(td.tipo);if(!activeFor(c,type).includes(kind))throw new HttpsError('permission-denied','Scheda non spettante.');if(kind==='consiglio'||kind==='istituto'||kind==='consulta'){const lists=kind==='consiglio'?(c.listeConsiglio?.[type]||{}):kind==='istituto'?(c.listeIstituto||{}):(c.listeConsulta||{});if(!v.lista||!lists[v.lista])throw new HttpsError('invalid-argument','Lista non valida.');const prefs=[v.p1,v.p2].map(norm).filter(Boolean);if(new Set(prefs).size!==prefs.length)throw new HttpsError('invalid-argument','Preferenze duplicate.');const max=Number(kind==='consiglio'?c.maxPrefConsiglio:kind==='istituto'?c.maxPrefIstituto:c.maxPrefConsulta)||0;if(prefs.length>max)throw new HttpsError('invalid-argument','Troppe preferenze.');const allowed=(lists[v.lista].candidati||[]).map(norm);for(const p of prefs)if(!allowed.includes(p))throw new HttpsError('invalid-argument','Candidato non appartenente alla lista.')}else if(!v.isBianca&&!norm(v.candidate1))throw new HttpsError('invalid-argument','Indicare un candidato o scheda bianca.')}
exports.validateVoterToken=onCall(async req=>{const token=norm(req.data?.token),year=req.data?.annoScolastico;if(!token||token.length>100)throw new HttpsError('invalid-argument','Token non valido.');const ph=await phase(year);if(ph.phase!=='OPEN')throw new HttpsError('failed-precondition','Votazione non aperta.');const ref=col('tokens',year).doc(token),snap=await ref.get();if(!snap.exists)throw new HttpsError('permission-denied','Credenziale non valida.');const d=snap.data()||{},f=flags(d),eligible=activeFor(ph.config,norm(d.tipo));const map={consiglio:'voted_consiglio',istituto:'voted_istituto',consulta:'voted_consulta',classeStudente:'voted_classe_studente',classeGenitore:'voted_classe_genitore'};if(eligible.every(k=>f[map[k]]))throw new HttpsError('failed-precondition','Tutte le schede risultano già concluse.');if(d.activeSessionHash&&d.sessionExpiresAt?.toMillis?.()>Date.now())throw new HttpsError('aborted','Esiste già una sessione attiva per questa credenziale.');const sid=randomId(),sh=hash(sid),exp=admin.firestore.Timestamp.fromMillis(Date.now()+SESSION_MS);await ref.update({activeSessionHash:sh,sessionExpiresAt:exp});return{sessionId:sid,tipo:norm(d.tipo),classe:norm(d.classe),indirizzo:norm(d.indirizzo),...f}});
exports.castVote=onCall(async req=>{const sid=String(req.data?.sessionId||''),year=req.data?.annoScolastico,ballots=req.data?.ballots;if(!sid||!ballots||typeof ballots!=='object')throw new HttpsError('invalid-argument','Sessione o schede mancanti.');const ph=await phase(year);if(ph.phase!=='OPEN')throw new HttpsError('failed-precondition','Votazione chiusa.');const sh=hash(sid),qs=await col('tokens',year).where('activeSessionHash','==',sh).limit(1).get();if(qs.empty)throw new HttpsError('permission-denied','Sessione non valida.');const tokenDoc=qs.docs[0],td=tokenDoc.data()||{};if(!td.sessionExpiresAt||td.sessionExpiresAt.toMillis()<Date.now())throw new HttpsError('deadline-exceeded','Sessione scaduta.');const entries=Object.entries(ballots);if(!entries.length)throw new HttpsError('invalid-argument','Nessuna scheda.');for(const[k,v]of entries)validateBallot(k,v,ph.config,td);await db.runTransaction(async tx=>{const fresh=(await tx.get(tokenDoc.ref)).data()||{};if(fresh.activeSessionHash!==sh)throw new HttpsError('aborted','Sessione già consumata.');for(const[k,v]of entries){const[cn,flag]=ballotMeta(k);if(fresh[flag])throw new HttpsError('already-exists','Scheda già votata.');const b=storedBallot(v,k,fresh);const ref=col(cn,year).doc(randomId(24));tx.create(ref,b);tx.update(tokenDoc.ref,{[flag]:true})}tx.update(tokenDoc.ref,{activeSessionHash:admin.firestore.FieldValue.delete(),sessionExpiresAt:admin.firestore.FieldValue.delete()})});return{ok:true}});
exports.commissionLogin=onCall(async req=>{const year=req.data?.annoScolastico,p=await findStaff(req.data?.username,year,'COMMISSIONE');if(!p||p.active===false||!verifyPwd(String(req.data?.password||''),p))throw new HttpsError('permission-denied','Credenziali non valide.');const ct=await staffCustomToken(p);return{customToken:ct,profile:{name:p.name,role:'COMMISSIONE',scopeClass:p.scopeClass||'TUTTE'}}});
exports.managementLogin=onCall(async req=>{const role=norm(req.data?.requestedRole);if(!STAFF_ROLES.has(role)||role==='COMMISSIONE')throw new HttpsError('invalid-argument','Ruolo non valido.');const p=await findStaff(req.data?.username,req.data?.annoScolastico,role);if(!p||p.active===false||!verifyPwd(String(req.data?.password||''),p))throw new HttpsError('permission-denied','Credenziali non valide.');return{customToken:await staffCustomToken(p),profile:{name:p.name,role,scopeClass:p.scopeClass||'TUTTE'}}});
exports.referentLogin=onCall(async req=>{const year=req.data?.annoScolastico,tipo=norm(req.data?.tipo),token=norm(req.data?.token);if(!['STUDENTE','GENITORE'].includes(tipo)||!token)throw new HttpsError('invalid-argument','Dati non validi.');const d=(await col('config',year).doc('referenti_keys').get()).data()||{},entry=d[token];if(!entry||norm(entry.tipo)!==tipo)throw new HttpsError('permission-denied','Codice referente non valido.');const uid=`ref_${hash(year+'|'+token).slice(0,32)}`;return{customToken:await admin.auth().createCustomToken(uid,{role:'REFERENTE',tipo,scopeClass:norm(entry.classe)}),tipo,classe:norm(entry.classe)}});
async function aggregate(year,scopeClass='TUTTE'){const names=['voti_consiglio','voti_istituto','voti_consulta','voti_classe_studenti','voti_classe_genitori'],out={totals:{}};for(const n of names){const s=await col(n,year).get(),arr=[];s.forEach(d=>{const x=d.data();if(scopeClass==='TUTTE'||norm(x.classe)===scopeClass)arr.push(x)});out.totals[n]=arr.length}return out}
exports.getAnonymousBallots=onCall(async req=>{const actor=requireAuth(req,['COMMISSIONE','DIRIGENTE','VICEPRESIDE','DSGA','SEGRETERIA','REFERENTE']),year=req.data?.annoScolastico,ph=await phase(year);if(actor.role==='COMMISSIONE'&&ph.phase!=='OPEN'){const name=String(req.data?.collection||'');if(!['voti_consiglio','voti_istituto','voti_consulta','voti_classe_studenti','voti_classe_genitori'].includes(name))return aggregate(year);const s=await col(name,year).get(),items=[];s.forEach(d=>items.push(d.data()));return{anonymousBallots:items,phase:ph.phase}}return{...(await aggregate(year,actor.scopeClass||'TUTTE')),phase:ph.phase,detailReleased:ph.phase==='RELEASED'}});
exports.getSecurityStatus=onCall(async req=>{const a=requireAuth(req,['COMMISSIONE','DIRIGENTE','VICEPRESIDE','DSGA','SEGRETERIA']);const ph=await phase(req.data?.annoScolastico);await audit(a,'SECURITY_STATUS',{annoScolastico:req.data?.annoScolastico});return{phase:ph.phase,controls:{ballotClientAccess:'DENY',identityBallotLink:'NOT_STORED',ballotTimestamp:'NOT_STORED',serverValidation:true,sessionTtlMinutes:15,auditAdmin:true}}});
function safeConfig(v,depth=0){if(depth>12)throw new HttpsError('invalid-argument','Configurazione troppo annidata.');if(v==null||typeof v==='boolean'||typeof v==='number')return;if(typeof v==='string'){if(v.length>8000||/[<>`]/.test(v))throw new HttpsError('invalid-argument','Valore configurazione non ammesso.');return}if(Array.isArray(v)){if(v.length>1000)throw new HttpsError('invalid-argument','Troppi elementi.');return v.forEach(x=>safeConfig(x,depth+1))}if(typeof v==='object')return Object.entries(v).forEach(([k,x])=>{if(['__proto__','prototype','constructor'].includes(k))throw new HttpsError('invalid-argument','Chiave non ammessa.');safeConfig(x,depth+1)});throw new HttpsError('invalid-argument','Tipo non ammesso.')}
exports.saveElectionConfig=onCall(async req=>{const a=requireAuth(req,['COMMISSIONE']),c=req.data?.config,y=c?.annoScolastico||req.data?.annoScolastico;safeConfig(c);if(JSON.stringify(c).length>700000)throw new HttpsError('invalid-argument','Configurazione troppo grande.');await db.runTransaction(async tx=>{tx.set(globalConfig(),{annoScolastico:y},{merge:true});tx.set(yearlyConfig(y),{...c,annoScolastico:y})});await audit(a,'SAVE_CONFIG',{annoScolastico:y});return{ok:true}});
exports.createStaffAccount=onCall(async req=>{const a=requireAuth(req,['COMMISSIONE']),year=req.data?.annoScolastico,role=norm(req.data?.role),username=String(req.data?.username||'').trim().toLowerCase(),name=String(req.data?.name||'').trim(),pw=String(req.data?.password||''),scopeClass=norm(req.data?.scopeClass||'TUTTE');if(!STAFF_ROLES.has(role)||!name||!/^[a-z0-9._-]{3,64}$/.test(username)||pw.length<12)throw new HttpsError('invalid-argument','Dati account non validi.');if(!(await col('gestione_accessi',year).where('username','==',username).limit(1).get()).empty)throw new HttpsError('already-exists','Username esistente.');const salt=crypto.randomBytes(24).toString('hex'),passwordHash=crypto.scryptSync(pw,salt,64).toString('hex');await col('gestione_accessi',year).add({name,username,passwordHash,passwordSalt:salt,role,scopeClass,active:true,createdAt:admin.firestore.FieldValue.serverTimestamp()});await audit(a,'CREATE_STAFF',{role,scopeClass,annoScolastico:year});return{ok:true}});
exports.setStaffAccountActive=onCall(async req=>{const a=requireAuth(req,['COMMISSIONE']),year=req.data?.annoScolastico,id=String(req.data?.id||'');if(!id)throw new HttpsError('invalid-argument','ID mancante.');await col('gestione_accessi',year).doc(id).update({active:!!req.data?.active});await audit(a,'SET_STAFF_ACTIVE',{annoScolastico:year});return{ok:true}});
exports.ensureReferentKeys=onCall(async req=>{const a=requireAuth(req,['COMMISSIONE']),year=req.data?.annoScolastico,tipo=norm(req.data?.tipo),classes=[...new Set((req.data?.classes||[]).map(norm).filter(Boolean))];if(!['STUDENTE','GENITORE'].includes(tipo)||!classes.length)throw new HttpsError('invalid-argument','Dati non validi.');const ref=col('config',year).doc('referenti_keys'),out={};await db.runTransaction(async tx=>{const s=await tx.get(ref),d=s.exists?s.data():{};for(const cl of classes){let found=Object.entries(d).find(([,v])=>norm(v.classe)===cl&&norm(v.tipo)===tipo);if(!found){const k=`REF-${tipo==='STUDENTE'?'STU':'GEN'}-${randomId(12).replace(/[^A-Z0-9]/gi,'').toUpperCase().slice(0,16)}`;d[k]={classe:cl,tipo};found=[k,d[k]]}out[found[0]]=found[1]}tx.set(ref,d)});await audit(a,'ENSURE_REFERENTS',{tipo,classCount:classes.length,annoScolastico:year});return{keys:out}});
exports.destructiveAction=onCall(async req=>{requireAuth(req,['COMMISSIONE']);throw new HttpsError('failed-precondition','Operazione distruttiva disabilitata. Usare procedura straordinaria verbalizzata e strumenti amministrativi separati.')});